name: Next.js CI/CD (EC2 Deployment)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ec2-3-8-182-132.eu-west-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."   # Send entire app
          target: "/home/ec2-user/acess-sec"
          overwrite: true
          strip_components: 1

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ec2-3-8-182-132.eu-west-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/acess-sec
            npm install
            npm run build
            pm2 restart next-app || pm2 start npm --name next-app -- start
            pm2 save
